### ISSUE TITLE
grunt-bower-tasks and gulp-bower are setup to install files using different strategies

### ISSUE THREAD

**Issue by johnpapa** [OmniSharp/generator-aspnet#116]
After talking to Shayne, this [PR](https://github.com/OmniSharp/generator-aspnet/pull/115) is likely not going to help as it fixes gulp but break grunt. 

When using grunt, the bootstrap files end up getting reorganized not only in the lib folder but also by component which drops the `dist` folder. First, I think there is little value and asking for trouble by reorganizing the bower files. Its fine to put them in lib, but restructuring is not very fruitful.

Case in point ... the gulp-bower package you use in the generator just install the bower files in lib. All done ... we're good right?

Nope

Now the `<script>` tag and CSS references need to point to different places for gulp vs grunt.

Here is what the template points to:

```
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
```

This works for grunt because the grunt plugin restructures the files. But it fails for gulp, which actually needs

```
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
```
### My Recommendation
- Consider using something besides grunt-bower-task as it is looking for a maintainer ... perhaps just use node and run bower install and set up the .bowerrc file to where you want it to go? I'd consider writing it yourself with grunt.
- Better yet, if the idea is to restructure so the bower files are exactly what is deployed, just copy the main files over. Pretty easy to do in gulp without a plugin (just src in and dest out). If you truly want the stuff in the lib folder to just be what is exposed on the web, then just copy those files using a custom gulp and grunt task.

**Comment by johnpapa** [comment]
also found that `_references.js` gets generated with a gruntfile reference, even when I use the --gulp option

**Comment by peterblazejewicz** [comment]
@spboyer @sayedihashimi  Do you guys have any insight how future VS will handle client-side bundling/optimisation? Any pointer? With the current version I'm using mix of VS tools in VS2013 + WebEssentials to build very efficient bundled and optimised content. Outside of VS we just use Grunt/Bower with bunch of configuration files to do the same for any type of projects. Exactly what @johnpapa wrote.

**Comment by xtianus79** [comment]
To this point... for the generator I organized I removed Bower:Install as it lead to much of the oddities that @johnpapa was speaking of.  The only way to get wiredep working was to have a direct file and folder relationship between bower_components and wwwroot directories.  

How did you guys end up adjusting this?

**Comment by xtianus79** [comment]
oh I forgot to mention the way I handled the solution was to do a copy and clean functionality through grunt upon certain grunt tasks.

**Comment by peterblazejewicz** [comment]
at work with VS2013 I use WebEssentials and C#/MVC built-in fetaures. Outside of VS2013 in other projects I use Grunt/Gulp and everything from Less/Sass and any kind of template language. I think that guys at MS have yet to decide how to provide nice tooling. Nice to see that John Papa is somehow involved into this, as they need solid help to provid flexible solution :+1:

**Comment by xtianus79** [comment]
What do you mean provide nice tooling?

**Comment by peterblazejewicz** [comment]
With VS2013 I use WebEssentials + VS tools for transpiling, bundling and minification. If I use NuGet packages and mentioned tools my team does not have to write any code for build phase.  With Grunt/Gulp/Bower/WebPack that's not the case. The `Web Application` ships with static client side CSS code. Say, Google's Web Starter Kit `template` implementation:
https://github.com/google/web-starter-kit/blob/master/gulpfile.js
It is used in `generator-mobile` directly `as is`. In `aspnet` generator we need something that works both in VS and outside of VS I think.

**Comment by xtianus79** [comment]
@peterblazejewicz but that is exactly how I setup generator aspnet-xtianus... yes it comes with foundation out of the box but anyone could simply delete the foundation bower dep and replace it with bootstrap. Now, to be completly accurate there would probably need to be a couple other adjustments because my setup is for a specific sass configuration to take the generated scss file to css and then move that to the appropriate folder upon compilation. I personally don't know if bootstrap is setup the exact same way.

Again, to Pappa's point the current way the web application is setup currently with bower:install leads to the "static" configuration of how it is setup.  That is why I got rid of it for my starter web template.  

I do agree with you completely that it needs to work both inside and outside of VS... but doesn't grunt, gulp, npm and bower cover that?  

when you say:
> at work with VS2013 I use WebEssentials and C#/MVC built-in fetaures. Outside of VS2013 in other projects I use Grunt/Gulp and everything from Less/Sass and any kind of template language. 

Isn't this the point of Vnext / Visual Studio 2015 and the embracing of the embedded first class citizens of NPM and Bower configurable by grunt or gulp?  

My question is why would I want to mess around with things that don't do the best they can do when I have complete disposal of the tools I need to do the task I when I need them?  For backend that would be VS tooling... for Frontend that would be NPM / Bower / Grunt / Gulp tooling no?

**Comment by sayedihashimi** [comment]
>@spboyer @sayedihashimi Do you guys have any insight how future VS will handle client-side bundling/optimisation? 

@madskristensen can you help answer this?

**Comment by madskristensen** [comment]
Using Gulp and/or Grunt

**Comment by sayedihashimi** [comment]
@madskristensen can you share the gulp/grunt file you currently have for beta4?

**Comment by johnpapa** [comment]
If you want help shaping that gulp file, lemme know. I'm working on an asp/net 5 generator for hottowel that will be all gulp.

**Comment by peterblazejewicz** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.

Thanks!
