### ISSUE TITLE
There seems to be some confusion about what is being used for copyTtpl vs simply copy and whitespacing

### ISSUE THREAD

**Issue by xtianus79** [OmniSharp/generator-aspnet#167]
I waited a while so things could progress on the VS VNext end and then update my fork.  LOL, well that was a bit painful... As change always is.  However, going through the lines of code I don't have a complete understanding of why copyTpl vs copy is utilized throughout the web template.  

I know what they do and perhaps it should be clear on when they should be used or not.  If I see CopyTpl I am assuming there is some lodash being passed through to replace some parameter the user put in i.e. the namespace being the applicationName... However, most of the time this is not the case and then in certain aspects where i think it would be the case, in my template it is, the directive isn't used.  i.e. gruntfile.js.  

I think perhaps it would be helpful for some standardization so coding additions and forked repos can follow a best practiced standard.  

Moreover, spacing... I am assuming spacing is a 4 space tab... Can we please hold to this?  I get merge conflicts that are so far off I have to basically rewrite everything to figure out what went on.  I believe a huge part of this is just how much the spacing changes form iteration to iteration. I may be wrong.  

Your thoughts.

**Comment by peterblazejewicz** [comment]
Don't assume, the project just uses current implementation and common tools:

- the current and next versions of Yeoman (this generator is not yet updated for this) use fs-mem package and EJS templating - not Lodash or Underscore. They have migrated to EJS because EJS gives more control on templating and generates better code/cleaner code compared to simpler Underscore templating:

https://github.com/yeoman/generator/issues/804

> We'll then use the copyTpl method to copy the file while processing the content as a template. copyTpl is using ejs template syntax.

https://github.com/sboudrias/mem-fs-editor#copytplfrom-to-context-settings
http://yeoman.io/authoring/file-system.html

This project has been already migrated to mem-fs module.

- there is EditorConfig file added to repository (it was missing from original release) that is added to help your code editor use project settings and that way to avoid merging conflicts

https://github.com/OmniSharp/generator-aspnet/blob/master/.editorconfig
https://github.com/OmniSharp/generator-aspnet/issues/113
https://github.com/OmniSharp/generator-aspnet/issues/130
