### ISSUE TITLE
Blocking issues with beta5

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#200]
We have the following blocking external errors for creating the beta5 templates.

 - ~~[web empty: several build errors](https://github.com/OmniSharp/generator-aspnet/pull/196#issuecomment-113624579)~~
 - ~~[web empty: kestrel: System.TypeInitializationException](https://github.com/OmniSharp/generator-aspnet/pull/196#issuecomment-113624579)~~
 - ~~[web no auth: kestrel: System.TypeInitializationException](https://github.com/OmniSharp/generator-aspnet/issues/190#issuecomment-113638131)~~
 - ~~[web individual: kestrel: System.TypeInitializationException](https://github.com/OmniSharp/generator-aspnet/issues/191#issuecomment-113632368)~~
 - ~~[web api: unable to restore](https://github.com/OmniSharp/generator-aspnet/pull/199#issue-89657045)~~
 - [web in general: stopping kestrel doesn't free the port](https://github.com/OmniSharp/generator-aspnet/issues/191#issuecomment-113790859)

~~Note: class library looks OK, but I have a pending question for @rustd at https://github.com/OmniSharp/generator-aspnet/issues/184#issuecomment-113583666~~

Console looks OK.

@peterblazejewicz @rustd @danroth27

**Comment by rustd** [comment]
Here are the changes needed to fix these errors
* project.json

Package name is Kestrel instead of Microsoft.AspNet.Server.Kestrel
    "Kestrel": "1.0.0-beta5",

The commands section should have
  "commands": {
    "kestrel": "Microsoft.AspNet.Hosting --server Kestrel --config hosting.ini",
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --config hosting.ini"
  },

* hosting.ini

This file should only have the following content
server.urls=http://localhost:5000

* Remove build numbers from packages. Packages should as follows 1.0.0-Beta5
Set NuGet package source and DNX_FEED to https://www.myget.org/f/aspnetbeta5/api/v2
Do not use the release/ dev feed

* BrowserLink
Remove BrowserLink package and the  app.UseBrowerLink(). from Startup.cs

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/KestrelHttpServer/issues/111
