### ISSUE TITLE
Angular project

### ISSUE THREAD

**Issue by rosieks** [OmniSharp/generator-aspnet#258]
Could you provide the whole Angular project that use gulp, bower, has tasks for running various tests, etc. Something similar to https://github.com/Swiip/generator-gulp-angular but that works with .NET on the server side.

**Comment by peterblazejewicz** [comment]
Note sure if that is a core feature of this generator - as the project tries to unify experience of using a template like generated content based on Visual Studio to other platforms. I think that as Angular already started appearing in the templates and they are people like John Papa involved: http://www.johnpapa.net/visual-studio-code-webinar/, there maybe will be something similar available in future iterations.
In the meantime: [ASP.NET 5 and AngularJS multipart series](http://stephenwalther.com/archive/2015/01/12/asp-net-5-and-angularjs-part-1-configuring-grunt-uglify-and-angularjs)

**Comment by sayedihashimi** [comment]
@rosieks I think that's a great idea for a new generator, perhaps `generator-aspnet-angular`. I have some comments about the goals of this generator and related generators at https://github.com/OmniSharp/generator-aspnet/wiki/goals-and-related-generators.

**Comment by sayedihashimi** [comment]
@rosieks if you would like to get started with a yo generator I can outline what is needed.

I think the best thing to do is to clone [generator-aspnet](https://github.com/OmniSharp/generator-aspnet) and publish as a new project named `generator-aspnet-semanticui`. Don't fork it because forks on github are not indexed.

From there the goal will be to keep that repo in line with releases of [generator-aspnet](https://github.com/OmniSharp/generator-aspnet) which is updated on every release of the asp.net 5 runtime to nuget.org.

We can us travis to automate the publish of the generated npm package to [npmjs.org](http://npmjs.org).

You can do this work in your own repo or we can create a new repo in the [OmniSharp org](https://github.com/OmniSharp). If you want to do this in OmniSharp I can do the following for you.

 - Create a new repo in [OmniSharp org](https://github.com/OmniSharp) that has the existing content from [generator-aspnet](https://github.com/OmniSharp/generator-aspnet)
 - Modify artifacts to use a new name for the npm package to be `generator-aspnet-angular`
 - Automate publish from `release` branch

We can remove the class library, console templates and Web API templates since they are not relevant. You can decided if you want to update the Nancy template or remove it. You can also add other new templates there beside the existing web templates that VS ships.

If you don't have the time to do the work right away then you can create a .zip file with the end result for the web templates and create issues in that repo and hopefully we can find someone who can work on it.
