### ISSUE TITLE
Upgrade to latest Gulp version

### ISSUE THREAD

**Issue by scottaddie** [OmniSharp/generator-aspnet#337]
I created a Web Application Basic and noticed the generator's package.json file references version 3.8.11 of Gulp. When the latest version of Gulp (3.9.0) is installed globally, the following warning appears when running a Gulp task:

Warning: gulp version mismatch:
Global gulp is 3.9.0
Local gulp is 3.8.11

The package.json file should be updated to reference 3.9.0.

![gulp_issue_screenshot](https://cloud.githubusercontent.com/assets/10702007/9705184/a9ef02fc-5481-11e5-9f43-64af8b05a688.png)

**Comment by peterblazejewicz** [comment]
@scottaddie 
Yes, I've seen the same.
Please upvote:
https://github.com/gulpjs/gulp/releases

@sayedihashimi 
The 3.8.11 is from Feb, the 3.9.* is from July. These are warnings and do not prevent from building:
https://github.com/gulpjs/gulp/releases

**Comment by peterblazejewicz** [comment]
note: review during beta8

**Comment by peterblazejewicz** [comment]
@scottaddie
Can I move this to @aspnet/tooling as issue? We use 'one-to-one' (nearly) copy of content that is primary created and documented by VS tooling team. If you agree, I'll create a ticket to propagate problem and close this one.
They should be aware of versions moving up (o gosh, there is Gulp v4 coming soon) as they are moving to RC1
Thanks!

**Comment by scottaddie** [comment]
@peterblazejewicz I am okay with you moving this issue over to aspnet/tooling. Please go ahead. With the breaking changes being introduced in Gulp 4, I assume they're already looking at that.

**Comment by peterblazejewicz** [comment]
@scottaddie 
Thanks! Moved to:
https://github.com/aspnet/Tooling/issues/215
Closing this one

**Comment by sayedihashimi** [comment]
I'd like to clarify one thing here. The [goals for `yo aspnet`](https://github.com/OmniSharp/generator-aspnet/wiki/goals-and-related-generators) include that the templates in yo aspnet be _equivalent_ to Visual Studio 2015 templates. This does not mean that the templates have to have the exact same content. What it really means is that when you use yo aspnet or Visual Studio to create an ASP.NET 5 project that users get the same basic functionality and can follow the same tutorials.

In addition to being equivalent to VS templates we have a commitment as the "official generators for ASP.NET 5" that we will release on the same day as runtime updates go out. With the support of the ASP.NET team of course.

So we have two ways that we can solve this.
 1. Try and align the templates to be exactly (or as close as possible) to content provided by VS
 1. Work with the community to make updates when it makes sense, but only those that won't break tutorials and overall experience

IMO 2 is a better option. With Visual Studio we (Microsoft) are limited in shipping updated OSS components because they need to be scanned before being shipped with VS. In `yo aspnet` we don't have to worry about those issues.

The risk with 2 is that it may be more work on our (community) side. If we diverge, when we get the content from the VS team we will need to translate that to the content that we have in `yo aspnet`. If we are all on board with maintaining those changes and continuing to meet our committment to the aspnet team by delivering the same day that ASP.NET 5 releases go out, I'm all for adding improvements to `yo aspnet` first and then using that to drive the templates that are shipped in VS.

So to be more specific, I think we should consider upgrading all OSS components to that latest versions that do not have breaking changes, and I think we should also consider using gulp in a way that most people familiar with gulp would expect. The gulp template we have in VS is not targeted to users who are familiar with gulp but instead users who may not be familiar with gulp. I think the yo aspnet users are far more likely to be existing gulp users.

Thoughts?

cc @shanselman @rustd

**Comment by spboyer** [comment]
Now that the templates are OSS - http://github.com/aspnet/templates it would be easier to manage these types of chnages we there a path for VStudio and this project to share the templates. A single source of the truth per se

**Comment by scottaddie** [comment]
@sayedihashimi I tend to favor option 2, and I'm happy to help out where I can. This is our chance to help push the templates forward and bring them closer to what the OSS best practices would prescribe. The ASP.NET team could consider what works well in the yo aspnet templates and then port those changes over to theirs.

**Comment by sayedihashimi** [comment]
@spboyer and @peterblazejewicz are the primary maintainers so it's up to them.

**Comment by peterblazejewicz** [comment]
I've been keeping voicing the idea that I'd like to provide the same experience for people without VS (and Windows OS) - the same easy way to start with the framework and tools - the ASP.NET 5 is to be xplat - why the experience for newcomers should be different? So I've *Enterprise* grade VS at work, but using Atom (+ @david-driscoll ) at OS X and I never touched ASP.NET 5 yet with VS. As people start usually from reading blogs/post or just listening and watching SH and other people, browsing through asp.net resources, most of them start with content authored by MS with VS anyway. Now that content is available under OSS umbrella of Github projects, so I tend to think that we first should follow steps of MS, help them to fix bugs, update quality of provided example content, etc, etc. So I try to propagate problems/topics first to upstream projects (think like option # 1), but as there are some differences/issues, there is a sense to update user experience of generator-aspnet. We have now `Dockerfile` shipping with templates. I'd fix Gulp here first if we had no other option - as users of generator at some point will see that warnings - and warnings are the worst thing to show to people starting with a framework (just terrible experience). For the same reason maybe we will have to modify web templates to use Gulp/Grunt task with better (or just proper) bower_components placement within a project and better management of content placed into `wwwroot/lib`.
Wrap up:
- first: # 2 if it fits upgrading user experience of the tool
- second: # 1 - in all other cases - as user experience needs to be the same. People can follow the same blog post using whatever platform they want.

**Comment by david-driscoll** [comment]
I like the idea of making sure that templates are consistent, because it allows us keep up to date with VS.

For today, I'm fine (not that I have much say :smile:) with keeping things like gulp and grunt up to date, so long as they're not breaking changes.   It will be up to the Microsoft team to keep the VS templates up to date on their own schedule.  We can of course as @peterblazejewicz says, try and get these changes back into https://github.com/aspnet/Templates.


Going forward (and perhaps this is a comment for a different issue) I'd love to see some automated way to pull what exists in the VS templates repo, into generator, and then it can be merged in fairly easily, taking care of the fact that we may have bumped versions on our end, etc.

**Comment by shanselman** [comment]
I think of yo aspnet as being "Stable" and I'd support some kind of yo aspnet-edge (not a good word anymore but you get the idea) that is more up to date, more cutting-edge.

**Comment by peterblazejewicz** [comment]
So we have got a green light (:green_heart:)

**Comment by david-driscoll** [comment]
To @shanselman's point an "edge" where we have some extra things would certainly make sense. For keeping minor version up to date, like gulp I think we should be safe to do so on stable because the VS templates will eventually get there.

I say go for it (but I'm only one voice) :green_apple: :green_book: :green_heart: :tea:

**Comment by spboyer** [comment]
I'm in favor of semver, meaning not locking to hard version numbers. I'd prefer ~3.3.9

**Comment by david-driscoll** [comment]
That might still have the warning (not tested).  Sadly it doesn't appear there is a clear picture of what was added between 3.8.11 and 3.9.0.  That said past history with that team, I wouldn't expect any breaking changes between minor versions, other wise the would call it out.

**Comment by scottaddie** [comment]
@david-driscoll I personally haven't encountered any breaking changes when upgrading Gulp from 3.8.11 to 3.9.0. The upgrade to 4.0 will be a different story.

**Comment by peterblazejewicz** [comment]
> That might still have the warning (not tested). Sadly it doesn't appear there is a clear picture of what was added between 3.8.11 and 3.9.0.

ES6 via Babel - we will be able to add -es6 switch and to render everything in ES6 :dancer: 
https://github.com/peterblazejewicz/aspnet5-web-gulp-babel-ts/blob/master/src-babel/gulpfile.babel.js

**Comment by david-driscoll** [comment]
Well I think it makes sense, it's a non-breaking change.  And then from here we can send a PR to the templates repo, and get them up to date as well.
