### ISSUE TITLE
New generator that supports semantic-ui

### ISSUE THREAD

**Issue by jjwilliams** [OmniSharp/generator-aspnet#558]
This is brought over from https://github.com/aspnet/Tooling/issues/97.

I've been playing with the semantic ui framework and must say - it is nice. I don't know if it's "better" than bootstrap, but I would love to get a generator going to support using semantic-ui easily.

Reason why it should be its own generator:

https://github.com/OmniSharp/generator-aspnet/issues/97#issuecomment-89181220

**Comment by peterblazejewicz** [comment]
The generator contributors are framework neutral I think. The first and foremost reason Bootstrap is used, is that generator reflects directly content from aspnet/Templates. And the reason why MS choosen Bootstrap was obvious when it was adopted by VS Tooling team:
http://www.hanselman.com/blog/VisualStudio2013RCForWebDevelopersOneASPNETBrowserLinkAndOurDirection.aspx.
It seems that they picked a good, basic tools/frameworks that simply most of the people use to better support framework proliferation. RubyOnRails or ExpressJS just creates template of MVC project, without frameworks included.

Having said that, unfortunately swapping BS to SUI is not a metter of flag, dependency change (Bower/Gulp/NPM) but also quite significant changes in markup. The markup in templates use Bootstrap specific components classes and components directly (alerts, forms inputs, etc). The SUI markup is different and would require entire rewrite of some parts (specifically in web project with authorization support).
The content that generator ships is just the same content as used in VS or documented in docs.asp.net. There are only couple of small, minor additions that simply lacked compared to VS (Docker support is primary value added by contributors, just because it is used in VS Studio and documented on docs.asp.net).
Thanks!

**Comment by jjwilliams** [comment]
Yes I was just starting a new thread on this repo, per issue https://github.com/aspnet/Tooling/issues/97 and @sayedihashimi's instructions.

**Comment by sayedihashimi** [comment]
I asked @jjwilliams to create an issue here to discuss for the following reasons.

 - So that he was aware of the project
 - He initially was thinking it would be better to add an option here for semantic ui. I pointed him to https://github.com/OmniSharp/generator-aspnet/issues/97#issuecomment-89181220. If he had any outstanding questions on that he could ask it here
 - In case he needs any pointers on how to get started or questions about best practices

It would be good for us to have a consistent process/structure to make it easy for users to contribute across template repos.

@jjwilliams what's your latest thoughts about creating a separate generator such as `generator-aspnet-semanticui`? If you're convinced that's the right approach then I can help you get started if you need. I think we can fork this repo and then go from there. I can help you automate publish to NPM like I have for this project, and am available for other items as well. Just let me know how I can help.

FYI we are currently going from `dnx` to `dotnet`. There will be a bunch of template changes due to that. I think it would make sense to wait until that release to go beyond a prototype for semantic ui, but that's really up to @jjwilliams.

**Comment by spboyer** [comment]
My two cents. With the changes to the underlying stuff, DNX etc, I'd vote to make at least a seperate branch with semantic UI. I'm not sure where we will end up with project generation yet either with ` dotnet new` And the CLI either.

**Comment by jjwilliams** [comment]
@sayedihashimi I agree with creating a separate generator (generator-aspnet-semantui). After looking at the code and reading your post in the other discussion - using a switch could get ugly.

How far off is the dnx to dotnet release? If it's awhile off I'd still like to start working on the generator to at least get my feet wet with yo.

Would my concerns mostly just be cshtml layout changes to stay somewhat consistent with vs's templates?

Do you recommend forking or cloning to my own repo to work on or do you want to put one up?

@spboyer I am moving in the direction of an entirely different repo from generator-aspnet so the generator-aspnet stays in line with what VS generates.

**Comment by jjwilliams** [comment]
This is my personal account, jjwilliams was my college github login and I need to stop using it as I no longer receive university email (those free private repos were nice while they lasted!). Please tag jackjwilliams in any further messages.

**Comment by jackjwilliams** [comment]
This is my personal account, jjwilliams was my college github login and I need to stop using it as I no longer receive university email (those free private repos were nice while they lasted!). Please tag jackjwilliams in any further messages.

**Comment by sayedihashimi** [comment]
@jackjwilliams I am fine with creating a repo here if you're committed to maintaining it. I created a repo for someone else a few months back on another generator and it was never even published to npm. I'd like to avoid that happening again. If you're committed to it then I can do the following (if there is no push back from other omnisharp members)

 - Create a new repo `generator-aspnet-semanticui`
 - Create a new group and add you as admin
 - Help you automate the publish process to npm

**Comment by jackjwilliams** [comment]
@sayedihashimi lets hold off on creating one in Omnisharp for now. I will work out of my repo for a bit to see how it goes, I've already ran into some issues with their gulp pipeline that have not been fixed.

**Comment by sayedihashimi** [comment]
@jackjwilliams ok sounds good

**Comment by jackjwilliams** [comment]
@sayedihashimi Could you possibly give me a short rundown of the flow of generator-aspnet? I've found a lot of the pieces but I'm not sure exactly where bower kicks off its install of dependencies after running yo aspnet.

**Comment by jackjwilliams** [comment]
@sayedihashimi I've got most of the web project UI View changes in place. Next I will start on the generator part. However, I think it's going to be pretty straight forward. It almost looks as though all I need to do is replace the templates\projects\web with my new project, making sure all yo tokens are still in place. Is there more to it?

**Comment by peterblazejewicz** [comment]
@jackjwilliams 
`bower.json` should be checked for different packages and in Razor urls should be changed as well as markup. The common problem to be aware is that by default your content is run in PRODUCTION environment, so static CDN resources are used. You need to run your tests with DEVELOPMENT settings to test local content installed via Bower (or what ever you decide).
Thanks!

**Comment by jackjwilliams** [comment]
@peterblazejewicz Thanks, the only modification to bower.json is the removal of bootstrap and the addition of semantic-ui. I'm almost done with all the styling / Razor changes. I noticed that about the PROD environment is run by default, I will look into that more.

**Comment by sayedihashimi** [comment]
@jackjwilliams 
>I noticed that about the PROD environment is run by default, I will look into that more.

That's the behavior by default from the ASP.NET runtime. It can be controlled via an env var. In VS it's set automatically to `Development`. We could add a note about this to the text that's displayed after the project is created if it's causing issues for users.

**Comment by spboyer** [comment]
To run it under Development do the following 
`dnx web ASPNET_ENV=Development`

**Comment by jackjwilliams** [comment]
Thanks - it wasn't really an issue, just required a little digging and reading the documentation. You may want to add it to initial readme just to save others time.

I'm wrapping up changes and have pushed an initial commit to

https://github.com/jackjwilliams/generator-aspnet-semanticui

**Todo**
Possibly remove other generators
Add documentation explaining how Semantic UI Validation was integrated with jquery unobtrusive validation

**Comment by jackjwilliams** [comment]
@sayedihashimi I think the bulk of the changes might be done, is there anything else you recommend doing? I thought about removing all other generators, but I think it'd be easier to keep the generator mostly the same except the views. Would make merging changes in easier for updates aye?

I realize this will all change for the ASP.NET Core 1.0 coming in the next few months, but I've learned quite a bit about Yeoman so it was worth it. 

I created a feature/experimental branch with an idea for using switches - it only took a couple of hours. The only parts of the generator that uses ANY ui libraries are web and webbasic that I have found. Developers can place their overridden views / js / css in the templates/common folder (need to refactor to templates/overrides). Then the web / webbasic copyTpl copies the normal project files, and afterwards any overrides a developer provides (overwriting the normal project files).

**Comment by sayedihashimi** [comment]
@jackjwilliams I think we should discuss with @spboyer @peterblazejewicz, either in a one off meeting or in the monthly OmniSharp meeting.

cc @david-driscoll

**Comment by jackjwilliams** [comment]
@sayedihashimi Sounds good, let me know if I need to do anything.

**Comment by sayedihashimi** [comment]
I think that @peterblazejewicz usually cannot make the monthly meeting due to time zone issues.

@peterblazejewicz @spboyer could we meet online sometime next week to discuss next steps here? If so @peterblazejewicz can you let me know the timezone you're in? I know that @spboyer is on EST. @jackjwilliams what time zone are you in?

**Comment by jackjwilliams** [comment]
I'm on CST @sayedihashimi

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
> so @peterblazejewicz can you let me know the timezone you're in?

CET (Central European) - GMT+1

**Comment by sayedihashimi** [comment]
Thanks Peter
@jackwilliams please email me at sayedha@microsoft.com and I'll try and coordinate a meeting.

**Comment by sayedihashimi** [comment]
Here is a link with our time zones included http://www.timeanddate.com/worldclock/meetingtime.html?iso=20160301&p1=234&p2=48&p3=179&p4=210. I'll email so that we can pick a day + time.

**Comment by peterblazejewicz** [comment]
closed-via: https://github.com/OmniSharp/generator-aspnet/commit/7ebcab15d2691d175878c707085897fb90f2d121
