### ISSUE TITLE
Update templates based on VS CTP6

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#70]
We should update the project templates to match what we have in VS 2015 CTP6. I briefly spoke to @spboyer and he is investigating this. Will assign the item to him for now. Shayne if you need help let us know.

**Comment by peterblazejewicz** [comment]
:+1:  (I don't have VS2015 - but as I wrote previously that is what I expect - to have the same content on *nix machine that in VS)

**Comment by sayedihashimi** [comment]
@peterblazejewicz some templates in VS have options like Auth which we don't have yet in yeoman. Maybe we can add those but maybe we should wait until things stabilize a bit. 

I'm chatting with @rustd and @coolcsh to see if we can have a single repo for templates which drive the following.

 - Visual Studio templates
 - Yeoman generators
 - Sublime extensions
 - Shell extensions
 - Whatever other editors need

We need a single source for VS project/item templates. From there we can create a build process which extracts files from the _official repo_ and generate templates for yeoman and editor specifics.

I think it would be easier to start with Item Templates but it doesn't really matter much which we do first. I'd like to see what @rustd thinks of this.

**Comment by sayedihashimi** [comment]
@peterblazejewicz FYI you can create a VS2015 CTP6 VM in Windows Azure. Click on the More Images link to get the VS CTP configs.

**Comment by spboyer** [comment]
Finding one issue with the web template, EntityFramework isn't fully baked.  Migrations are not complete and are currently mocked in the template.  In order to support on OSX you must use EntityFramework.InMemory, however there is a new/existing error introduced in beta3 - https://github.com/aspnet/HttpAbstractions/issues/203
Looking for ideas here. 

Other note: Commented out `"Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta3"` from `project.json` as it does not restore from nuget using `kpm restore` , getting the following in terminal

`Unable to locate Microsoft.VisualStudio.Web.BrowserLink.Loader >= 14.0.0-beta3`

Seeing as how this is a Visual Studio specific assembly, it was rem and the `app.UseBrowerLink()` was also rem in `Startup.cs`

I am assuming the interest to to keep the generator and templates here as xplat as possible.

webapi and empty are ready with test coverage.  Waiting for thoughts on the web template.

@sayedihashimi @shanselman

**Comment by sayedihashimi** [comment]
Thanks @spboyer 

>Finding one issue with the web template, EntityFramework isn't fully baked. Migrations are not complete and are currently mocked in the template. In order to support on OSX you must use EntityFramework.InMemory, however there is a new/existing error introduced in beta3 - aspnet/HttpAbstractions#203
Looking for ideas here. 

I think some of these issues may take time to solve. Whenever we run into a blocking issue we should create an issue (like you have in this case) and make sure to indicate that it's blocking xplat scenarios.

In the mean time perhaps we should trim down the template to not rely on a DB? Once we get unblocked on the DB then we can add it back and get to parity with VS. Thoughts?

>Other note: Commented out "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta3" from >project.json as it does not restore from nuget using kpm restore , getting the following in terminal
>
>Seeing as how this is a Visual Studio specific assembly, it was rem and the app.UseBrowerLink() >was also rem in Startup.cs
>
>I am assuming the interest to to keep the generator and templates here as xplat as possible.

Sounds good, yes we should try and be as xplat as possible

**Comment by spboyer** [comment]
@sayedihashimi commented the `Register` link from the _Layout.cshtml and set some ` if mono` on the DB functionality to gain a full web template.

**Comment by sayedihashimi** [comment]
@spboyer ok sounds good thanks.

**Comment by spboyer** [comment]
v 0.0.31 published. Blog post coming asap.
