### ISSUE TITLE
Consider leveraging jspm?

### ISSUE THREAD

**Issue by jack4it** [OmniSharp/generator-aspnet#85]
JSPM looks very promising regarding client side package management and also ES6 compatible module loading. Will this generator a good place to start to leverage this great tool?

**Comment by peterblazejewicz** [comment]
I think the generator is developed on the promise to deliver the same experience for creating C#/.NET projects that are available for users with MS Visual Studio (vNext). So it ships with only those libraries/features/solutions that are available out-of-the box in MS VisualStudio (no extension added, no additional tools installed).
Also cast a vote here, as feature in subject is not existent:
http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/7017377-support-for-es6-modules

**Comment by sayedihashimi** [comment]
>I think the generator is developed on the promise to deliver the same experience for creating C#/.NET projects that are available for users with MS Visual Studio (vNext).

When using the yo generators ***you should be able to create the same projects and files as Visual Studio*** but we ***should not limit ourselves*** to what VS has. We recently reached parity with VS which I'm really happy about (_thanks everyone who helped_). We (_the asp.net community_) can create templates better and faster that Microsoft can. In the long term I'd like for VS to pull template content from this repo or a related one created and owned by the community.

Since yo generators are invoked on the command line we have the ability to provide for a broader set of options than what can be presented in VS. For example there are several yo generators which have optional settings which can be presented. One good example for us would be grunt or gulp. 

We can also provide new options which may not be available in VS, like the idea here.

Whenever we do add content which is above and beyond what VS has we have to ensure that it's high quality content and that it aligns with asp.net 5 best practices. 

In cases where there will be a significant addition to the generators I'd like to propose the following steps.

1. Create a new issue so that we can discuss the idea
1. Submit a PR with the proposed updates so that everyone can try it out
1. See what everyone here thinks
1. Get input of the asp.net team

I will be on the hook for getting the feedback from the asp.net team to ensure that we are following best practices and aligning with future goals of asp.net/VS.

Thoughts?

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
Maybe I was not clear: I hope that generator will be able to create a content that is portable - I want to be able to create a project on *nix machine in such way, that another folk could open in VS - and other way around. I work at company with exclusive C# stack, so we literally __brick walled external contractor(s)__ with only *nix machine - or just __without VS installed on Win machine__. I hope that vNext - including generator - will allow to break this wall (I've worked mostly in startups with stacks that were based on open source components and can run everywhere).
I agree that some sugar can be added to generator features though - but as addition to *core* features.

**Comment by sayedihashimi** [comment]
"I hope that generator will be able to create a content that is portable"
Yes, completely agree.

In this case VS editors do not support import/export but the asp.net runtime supports everything fine. Since it's a bug that VS doesn't support those it's ok to create content in generators containing it. Hopefully we can get the support soon.

**Comment by spboyer** [comment]
@odetocode has a good post here - http://odetocode.com/blogs/scott/archive/2015/02/18/using-jspm-with-visual-studio-2015-and-asp-net-5.aspx showing how to setup jspm.  I could create an option for the project templates --jspm to use as an optional to bring it in. Thoughts?

@sayedihashimi

**Comment by OdeToCode** [comment]
+1 ;)

**Comment by sayedihashimi** [comment]
Lets try it out, later we can add a "show additional options" and prompt for this and other choices like grunt/gulp/etc.

Can you send a PR, then I can review it with the team?

**Comment by peterblazejewicz** [comment]
+1

**Comment by jack4it** [comment]
Looking forward to it...

**Comment by peterblazejewicz** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.

Thanks!
