### ISSUE TITLE
"dotnet new" versus "yo aspnet"

### ISSUE THREAD

**Issue by shawnwildermuth** [OmniSharp/generator-aspnet#858]
Any ideas on what the plan is for supporting this generator versus the dotnet new syntax that has been added to dotnet? If both are going to be updated going forward, that's great...just trying to see which has a longer support life.

**Comment by peterblazejewicz** [comment]
There are more tools. There is also [aspnet/Scaffolding](https://github.com/aspnet/Scaffolding). Basically all ecosystem seems migrating to `.csproj` in content and tool integration, so that's safe to wait and see the outcome.
@sayedihashimi If you have time for 2c

**Comment by shawnwildermuth** [comment]
Scoffolding is VS specific, no? I'm thinking of the cross-plat stuff (Mac and Linux as well as VS Code users on Windows).

**Comment by peterblazejewicz** [comment]
> Scoffolding is VS specific, no?

No, it could be plugged into `dotnet cli`. 
There was such idea from the beginning:
https://github.com/dotnet/cli/issues/515
The syntax is clumsy (at least):
```
dotnet aspnet-codegenerator --project /Users/coreapps/CoreWebApp2 controller --force --controllerName MoviesController --model CoreWebApp2.Models.Movie --dataContext CoreWebApp2.Data.ApplicationDbContext --relativeFolderPath Controllers --controllerNamespace CoreWebApp2.Controllers --useDefaultLayout
```
https://github.com/OmniSharp/generator-aspnet/issues/857#issuecomment-269393176
For some folks - including me - the only problem is the flux in the ecosystem itself now:
https://github.com/OmniSharp/generator-aspnet/issues/846#issuecomment-265775226

**Comment by sayedihashimi** [comment]
Thanks for the comments. A while back I shared my thoughts at https://github.com/dotnet/cli/issues/2052#issuecomment-207031714. See the FAQ section for yo aspnet content.

The general gist of the idea is that we have a lot of usage in `yo aspnet` and many people love the existing workflow from yeoman. So to that end we should continue supporting `yo aspnet`. Under the covers `dotnet new` will be using the [template engine](https://github.com/dotnet/templating) which is a self-contained core app that can be used to create templates. The idea is to integrate that template engine into `yo aspnet`. Today under the covers `yo aspnet` creates the files using [ejs](http://ejs.co/). The idea is to switch that out by invoking the template engine. The benefit here will be that we can share templates across products and it frees the community up to do more interesting work on top of it.

I think we've reached a point where we can start the work to integrate the template engine into `yo aspnet`. @peterblazejewicz what's your thoughts on the best way for us to get started there? Should I setup a meeting so that we can go over the template engine and dotnet new?

First I'd like to get `yo aspnet` up to parity and invoking the template engine. After we get there the maintenance cost for the templates themselves that are shipped with VS should be minimal. I'm hoping that after that we can work together to create a broader set of templates and more options from the community.

cc @mlorbetske @seancpeters

**Comment by peterblazejewicz** [comment]
> I think we've reached a point where we can start the work to integrate the template engine into yo aspnet. @peterblazejewicz what's your thoughts on the best way for us to get started there? Should I setup a meeting so that we can go over the template engine and dotnet new?

@sayedihashimi Frankly speaking - I just need you to ask here and there within MS what is the status of tooling right now (as the things are less transparent from some time) - so we could say, `OK, go ahead with {VERSION} release` - that is we need to be sure which runtime version should be installed and work with. TL;DR: which release it would be named after

I'd first rewrite content to match VS templates, left everything here supporting Node 4 (still active LTS unitl 2017-04-01 [sic!]) and only after new content is released migrate generator itself to support Node 6 (but only if generator tool remains an option compared to `dotnet-cli` features to not split efforts and user experiences)

Thanks!

**Comment by sayedihashimi** [comment]
@peterblazejewicz I'm on the tooling team so I can help you with any questions you have there.
WRT to `dotnet new` it's being release in RC.3 soon hopefully. Maybe we should wait until it gets released so that people get a chance to play with it and then we can circle back here to discuss how to integrate it.

**Comment by spboyer** [comment]
There's a lot of functionality here that the templating engine is not offering.  Are we looking to use the engine as a base replacement and keep the other items? i.e. Subgenerators etc?

**Comment by mlorbetske** [comment]
@spboyer could you be more specific about the features that are missing? Talking about the items from a scenario perspective would be the most helpful, we'd love to know what specifically we're missing so we can add it or expose functionality that we already have that isn't discoverable.

**Comment by sayedihashimi** [comment]
@spboyer 
>Are we looking to use the engine as a base replacement and keep the other items? i.e. Subgenerators etc?

The end user shouldn't see any difference. We will keep the subgenerators as they are. The idea is to keep the user experience the same as it is today (i.e. with using standard yo calls like we do today). Then we just call the template engine to create the project in the destination. 

For subgenerators specifically, we'll keep those as they are for now because we don't have many item template ready for `dotnet new`. Later once we have, we can update the subgenerators to call the template engine to crate the file(s).

**Comment by spboyer** [comment]
In the latest cli, there is a new command `new3` that has the following templates and options.

```
$ dotnet new3
Template Instantiation Commands for .NET Core CLI.

Usage: dotnet new3 [arguments] [options]

Arguments:
  template  The template to instantiate.

Options:
  -l|--list         List templates containing the specified name.
  -lang|--language  Specifies the language of the template to create
  -n|--name         The name for the output being created. If no name is specified, the name of the current directory is used.
  -o|--output       Location to place the generated output.
  -h|--help         Displays help for this command.
  -all|--show-all   Shows all templates

Templates                            Short Name      Language      Tags
---------------------------------------------------------------------------------
Console Application                  console         [C#], F#      Common/Console
Class library                        classlib        [C#], F#      Common/Library
Unit Test Project                    mstest          [C#], F#      Test/MSTest
xUnit Test Project                   xunit           [C#], F#      Test/xUnit
Empty ASP.NET Web Application        web             [C#]          Web/Empty
MVC ASP.NET Web Application          mvc             [C#], F#      Web/MVC
Web API ASP.NET Web Application      webapi          [C#]          Web/WebAPI

Examples:
    dotnet new3 mvc --auth None --framework 1.0
    dotnet new3 xunit
    dotnet new3 --help
```

**Comment by spboyer** [comment]
@mlorbetske to answer your question, it is the items like the sub-generators (File-Add New Item). All of the core project types are there, with the exception of Nancy.

**Comment by sayedihashimi** [comment]
@spboyer 
>In the latest cli, there is a new command new3 that has the following templates and options.

Yes, and in a future release that will replace `dotnet new`. `new3` is built on top of the "Template Engine", and it's that "Template Engine" component that we are thinking we can leverage in `yo aspnet`. The templates are served from NuGet packages and third parties can add new templates. For `yo aspnet` the idea is that we would keep the existing code that handles the user interaction and then under the covers we call Template Engine APIs to generate the project. Does that make sense?

FYI for scenarios like Nancy with `new3` it's possible to create a template and then have different packages to service C#, F#, Nancy, etc.

@spboyer @peterblazejewicz if you guys are interested I'll setup a 1 hour Skype call so that we can go over `dotnet new3` and the "Template Engine".

**Comment by spboyer** [comment]
I have to write docs on it, so we should talk anyway +1 @sayedihashimi

**Comment by sayedihashimi** [comment]
@spboyer OK I will email you and @peterblazejewicz

**Comment by peterblazejewicz** [comment]
@spboyer 
which version of runtime have you installed to have this `new3` 
@spboyer @sayedihashimi got the mail

**Comment by spboyer** [comment]
got to https://github.com/dotnet/cli#installers-and-binaries

1.0.0-rc4-004530

**Comment by peterblazejewicz** [comment]
@sayedihashimi @mlorbetske 
Is the content from https://github.com/dotnet/templating suitable for the rewrite/update in generator? If so, which branch should be used and followed for most recent content?

**Comment by peterblazejewicz** [comment]
The dotnet/templating project has section about roadmap:
https://github.com/dotnet/templating#roadmap
