### ISSUE TITLE
minimatch warning message about DoS vulnerability when installing generator-aspnet

### ISSUE THREAD

**Issue by ggirard07** [OmniSharp/generator-aspnet#859]
### Short issue description
The yeoman-genarator package version currently used seems outdated and relies on minimatch package version which produce a not so friendly warning at install time:
`npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

The only dependency I found to minimatch 2.0.10 is due to yoeman-generator 0.19.2... which used a serie of dependency leading to this precise minimatch version. Yeoman-generator has moved to a new dependency since 0.21.0 has been released.
```
C:\Users\me\Desktop\Test TS>npm ls --global  minimatch
C:\Users\me\AppData\Roaming\npm
+-- generator-aspnet@0.2.5
| +-- findup-sync@0.3.0
| | `-- glob@5.0.15
| |   `-- minimatch@3.0.3
| `-- yeoman-generator@0.19.2
|   `-- findup-sync@0.2.1
|     `-- glob@4.3.5
|       `-- minimatch@2.0.10
`-- yo@1.8.5
  `-- yeoman-doctor@2.1.0
    `-- twig@0.8.9
      `-- minimatch@3.0.3
```

I am completely new to ASP.Net Core, Yeoman and all the web stuff... so it is fairly difficult to evaluate the complexity of moving to a newer yoeman-generator version or staying with this minimatch warning :)

### Expected behavior
No "your PC is going to die" warning message...

### Actual behavior
"your PC is going to die" warning message...

### Steps to reproduce the behavior
1. choco install nodejs
2. npm install -g yo bower generator-aspnet
3. check warnings produce by installation

----
#### OS version (Win/Mac/\*Nix?)
Windows 10

#### NodeJS version
```
C:\Users\me\Desktop\Test TS>node --version
v7.3.0
```

#### Yeoman version
```
C:\Users\me\Desktop\Test TS>yo --version
1.8.5
```

#### Generator version
```
C:\Users\me\Desktop\Test TS>npm list -g generator-aspnet
C:\Users\me\AppData\Roaming\npm
`-- generator-aspnet@0.2.5
```

**Comment by peterblazejewicz** [comment]
The dependencies will be udpated, we have discussed that here already, e.g.:
https://github.com/OmniSharp/generator-aspnet/issues/858
but after this task (unless required otherwise):
https://github.com/OmniSharp/generator-aspnet/issues/846
I've tried on forked branch to update deps couple of times and most of things breaks in tests implementation. The deps and generator/subgenerators code updates are not trivial, but well documented:
https://github.com/yeoman/yeoman.github.io/blob/a87b3452377b1b232145f910d6a945804bf84d2c/app/_posts/blog/2016-12-03-hello-generator-1.0.md
The tests are worst to update, as they broke and require implementation changes (they are expected to broke when upgrading Yo version itself and when upgrading Node js version from 4.* to 6.* for local tests)
Thanks!
