### ISSUE TITLE
Can find project.json inside of new project

### ISSUE THREAD

**Issue by rheid** [OmniSharp/generator-aspnet#927]
### Short issue description
dotnet restore
warn : The folder '/Users/rheid/Development/WebApps/WebApplication/WebApplication' does not contain a project to restore.

### Expected behavior
Restores the dependencies and tools of a project.

### Actual behavior
Does not contain a project to restore. Did not find the project.json inside the project

### Steps to reproduce the behavior

yo aspnet
cd "WebApplication"
dotnet restore

----
#### OS version (Win/Mac/\*Nix?)

Mac

#### Dotnet version

.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64

#### NodeJS version
v7.3.0

#### Yeoman version
1.8.5

#### Generator version
── generator-aspnet@0.3.1

**Comment by arukomp** [comment]
The updated generator uses the new MSBuild for .NET Core process, which means the dependencies are stored in the .csproj file and the project.json is now gone.

You can either upgrade your .Net Core tooling to the newest MSBuild preview version, or downgrade this generator.

**Comment by rheid** [comment]
Thank you very much. Do you have a link for me to setup MSBuild on Mac?

**Comment by peterblazejewicz** [comment]
> Do you have a link for me to setup MSBuild on Mac?

You should not have to do this. It should be a part of updated dotnet runtime download (RC4).
All required tooling to build and run updated content are expected to be part of runtime (i've been porting all content for RC4 and tried this first hand (dotnet/templating#266):
http://tattoocoder.com/exploring-the-new-dotnet-cli/

@arukomp Thanks!

**Comment by computerex** [comment]
Your update broke this tutorial: https://docs.microsoft.com/en-us/aspnet/core/tutorials/your-first-mac-aspnet

**Comment by peterblazejewicz** [comment]
@computerex 
I understand. The recent update to yo generator has to be done as MS released RC4:
https://blogs.msdn.microsoft.com/dotnet/2017/02/07/announcing-net-core-tools-updates-in-vs-2017-rc/
No docs have been updated yet to discuss new tooling and dotnet features I believe:
https://docs.microsoft.com/en-us/search/index?search=csproj&scope=ASP.NET+Core

**Comment by computerex** [comment]
Some additional information for those interested:

https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/ProjectJsonToCSProj.md
https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/
https://github.com/dotnet/cli

Anyone know when we can expect a stable release of Core 1.0 that doesn't involve changes like these?

**Comment by KidSysco** [comment]
I tried it over the weekend on my Mac and it did not work. Without the project.json I can not follow the Getting Started Tutorials because commands like dotnet restore and such do not work.

Any idea on how to downgrade the generator?

**Comment by dbkvn** [comment]
I'm having the same issue on OS X as well, unfortunately.

**Comment by peterblazejewicz** [comment]
@KidSysco 
To make sure that you're using the version supporting `project.json`:
```bash
npm install -g genator-aspnet@0.2.6
```
The `0.3.*` version supports only `.csproj` content

This website lists all .Net Core download packages:
https://github.com/dotnet/core/blob/master/release-notes/download-archive.md

**Comment by mplacona** [comment]
For any future reference, the command above has a typo, which took me about 5 minutes to notice 😂. It should be:

`npm install -g generator-aspnet@0.2.6`

**Comment by stefanhendriks** [comment]
I installed the latest `dotnet` core runtime. Latest of this generator and ran into this problem. So some things are out of sync. @mplacona saved my day. thx!

**Comment by ckrassas** [comment]
Been dealing with this issue for a couple of days. Thanks to all for the info. Two resolutions:

From @mplacona 
`npm install -g generator-aspnet@0.2.6`
or 
use the the latest version just install the latest version of DotNet from: 
[https://github.com/dotnet/cli](https://github.com/dotnet/cli)

**Comment by peterblazejewicz** [comment]
> the command above has a typo,

Sorry folks!

**Comment by spboyer** [comment]
@computerex 

>Your update broke this tutorial: https://docs.microsoft.com/en-us/aspnet/core/tutorials/your-first-mac-aspnet

I'll be updating this tutorial asap.

**Comment by ckrassas** [comment]
> Been dealing with this issue for a couple of days. Thanks to all for the info. It really has to do with what version of dotnet core sdk is installed. To find out which version you have just dotnet --version

> Two resolutions:
From @mplacona
npm install -g generator-aspnet@0.2.6
or
use the the latest version just install the latest version of DotNet from:
https://github.com/dotnet/cli
The latest version download worked right away for me on Mac OS X Sierra.

Just wanted to update everyone with my experience as it can help many of you.
After taking a look at @computerex reply to the issue it seems that you can still run the `dotnet restore` and other commands with the project.json file instead of a .csproj file. Take a look at the [https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/ProjectJsonToCSProj.md](url) as it explains some of these things. 

You can have multiple versions of the .NET Core installed and while using a global.json file you can tell it to use an older version of dotnet. Instead of running a migration and running into issues. This should help since most tutorials out there are still using older versions. Hope this helps..

**Comment by cosmoKenney** [comment]
Can't open the .csproj in VS 2015. Is this latest generator only producing VS 2017 project files?

**Comment by peterblazejewicz** [comment]
@cosmoKenney 
The VS 2015 does not support .NET Core based on .csproj (and as I understand there is no intention to support this):
https://github.com/dotnet/cli/issues/5725

**Comment by MikeInSwitzerland** [comment]
It's now November 2017.  I've just downloaded the latest npm (v5.5.1), the latest Visual Studio 2017 Enterprise edition, the latest node.js.... and this issue is _still_ there.

I create a new project using "dotnet new mvc -au Individual -f netcoreapp2.0" and the resulting files don't include a "project.json" file, so "npm start" fails miserably, with a "no such file or directory, open 'C:\Projects\demo\package.json'" error.

This stuff is flaky as hell, and wasting tens of hours of my time.  I've never had a technology where I can't even follow up-to-date tutorials on the Microsoft, CodeProject or PluralSight websites...

Are there _any_ tutorials which are up-to-date, and can show me how to properly use this stuff ?

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
